### ISSUE TITLE
Process Flow Chart: Create a Log In Page : Brand New User

### ISSUE THREAD

**Issue by Mlusso06** [habibtaghavi08/DateCreate#14]
As a new user I can register for an account by creating a login and providing my contact information

**Comment by Mlusso06** [comment]
Here are some Possible Conditions of Satisfaction (CoS) for the following Story:
	Task 1: A username must be provided that is between 4 and 20 characters in length
	Task 2: The username must be unique
	Task 3: The username is case sensitive
	Task 4: The username can contain only numbers and letters
	Task 5: A password must be provided that is between 4 and 20 characters in length
	Task 6: The password can contain only numbers and letters
	Task 7: The password must contain at least 1 number and 1 letter
	Task 8: An email must be provided
	Task 9: The email must be entered in the valid format
	Task 10: The email must be confirmed via a double entry
	Task 11: The email must not already exist in the system
	Task 12: Validation error messages that should appear if a field entry is missing or invalid

**Comment by d-taylor6403** [comment]
[newuser.pdf](https://github.com/habibtaghavi08/DateCreate/files/4637621/newuser.pdf)
