### ISSUE TITLE
Process Flow Chart: Create a Log in Page : Existing User

### ISSUE THREAD

**Issue by Mlusso06** [habibtaghavi08/DateCreate#15]
As an existing user I can login to my account with my username and password

**Comment by Mlusso06** [comment]
Task 1: Enter unique User Name (in Database)
Task 2: Enter a case sensitive UserName
Task 3: Enter a password that matches unique name's password 
Task 4: Enter a password that is case sensitive 
Task 5: Click Submit button (Log In)
Task 6: Validate (if NoMatch) go to a page or comment to enter Valid username or / and Passwrd
Task 7: Open link to allow user to go to Profile / (saved / future/ Filter)

**Comment by d-taylor6403** [comment]
[existinguser.pdf](https://github.com/habibtaghavi08/DateCreate/files/4637625/existinguser.pdf)
