### ISSUE TITLE
Process Flow Chart: As as user I can Filter the criteria for the Date

### ISSUE THREAD

**Issue by Mlusso06** [habibtaghavi08/DateCreate#17]

**Comment by Mlusso06** [comment]
Task 1: User enters (5) digit (Valid) Zip code 
Task 2: User enters a mile validation for location of Date opportunity (5, 25, 50, 100 mile)
Task 3: Filter Pull Down a list of Date Values $ (for budget) 
Task 4: User to select Day or Night  
Task 5:

**Comment by d-taylor6403** [comment]
- [ ] Task 1: The zip code must be 5 digits

- [ ] Task 2: The mile validation field must contain a value (5,25,50,100 mile)

- [ ] Task 3: The Budget Criteria must contain 1 selection ($, $$, $$$ and $$$$)

- [ ] Task 4: The Time of Day Criteria must contain 1 selection 
                   (Day (7:00-17:00(7am-5pm) or Night(18:00-03:00(6pm-3am)

- [ ] Task 5: The Activity must contain 1 selection ( Activity or Event)

- [ ] Task 6: If Event is selected, Event Type must contain 1 selection 
                    (https://www.yelp.com/developers/documentation/v3/event_categories_list).

- [ ] Task 7: If Activity is selected, Activity Type must contain 1 selection 
                     (https://www.yelp.com/developers/documentation/v3/all_category_list *Needs to be 
                      narrowed down)

- [ ] Task 8: The Restaurant Type must contain 1 selection            
                   (https://www.yelp.com/developers/documentation/v3/all_category_list *Needs to be 
                    narrowed down)

- [ ] Task 9: The Popularity Filter is optional


Note: Yelp API (https://www.yelp.com/developers)

**Comment by d-taylor6403** [comment]
[Filter Page Process Flow.pdf](https://github.com/habibtaghavi08/DateCreate/files/4619215/Filter.Page.Process.Flow.pdf)

**Comment by d-taylor6403** [comment]
[Filter Page Process Flow.pdf](https://github.com/habibtaghavi08/DateCreate/files/4637631/Filter.Page.Process.Flow.pdf)
