### ISSUE TITLE
Process Flow Chart: User can View "Future or Planned Dates"

### ISSUE THREAD

**Issue by Mlusso06** [habibtaghavi08/DateCreate#19]
As a user I can view "Future" Dates I would like to go on.

**Comment by Mlusso06** [comment]
Task 1: User can view all selected saved dates from shuffle
Task 2: User can select date (will view Date name, cost, location) (similar to filter)
Task 3:

**Comment by habibtaghavi08** [comment]
just slacked you Mike and Dannieellee the final copies of both planned and confirmed as we'll !! let me know so I can update when I get Home Please
